### ISSUE TITLE
Unit test: Cannot find module 'Vue' from 'vue-form-json-schema.umd.js'

### ISSUE THREAD

**Issue by karladler** [jarvelov/vue-form-json-schema#74]
When running my unit tests in the CI I get the following error:

```
Cannot find module 'Vue' from 'vue-form-json-schema.umd.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at exports (node_modules/vue-form-json-schema/dist/webpack:/VueFormJsonSchema/webpack/universalModuleDefinition:5:40)
      at Object.<anonymous> (node_modules/vue-form-json-schema/dist/webpack:/VueFormJsonSchema/webpack/bootstrap:9:39)
```

locally the test works pretty fine.

My test file looks like this:

```
import { mount, Wrapper, createLocalVue } from '@vue/test-utils';
import Vue from 'vue';
import VueCompositionApi from '@vue/composition-api';
import VueFormJsonSchema from 'vue-form-json-schema';

import Register from '@/views/Component.vue';

let wrapper: Wrapper<Vue>;

beforeEach(() => {
  const localVue = createLocalVue();
  localVue.use(VueCompositionApi);
  localVue.use(VueFormJsonSchema);
  wrapper = mount(Component, {
    localVue
  });
});
```

Has anybody an idea how to fix this?

**Comment by jarvelov** [comment]
Hi Karl!

It looks like the UMD version is used instead of the ESM version. What happens if you change your import in your test file to explicitly use the ESM version?

Replace

`import VueFormJsonSchema from 'vue-form-json-schema';`

with

`import VueFormJsonSchema from 'vue-form-json-schema/dist/vue-form-json-schema.esm.js';`

**Comment by nexorianus** [comment]
I am having the same Problem.
running the tests on my local machine (Node 14.16.0) is all fine. But once i push it to git, and jenkins takes over the automated build it fails with exactly the same error as the OP.
```
FAIL src/components/utils/dynamicForm/dynamicForm.spec.js
  ● Test suite failed to run
    Cannot find module 'Vue' from 'vue-form-json-schema.umd.js'

      at Resolver.resolveModule (node_modules/jest-runner/node_modules/jest-resolve/build/index.js:259:17)
      at exports (node_modules/vue-form-json-schema/dist/webpack:/VueFormJsonSchema/webpack/universalModuleDefinition:5:40)
      at Object.<anonymous> (node_modules/vue-form-json-schema/dist/webpack:/VueFormJsonSchema/webpack/bootstrap:9:39)
```

Node versions on Jenkins and local are identical.
Currently installed: `vue-form-json-schema@2.8.2`

Tests are run with `vue-cli-service test:unit --coverage`

`"@vue/cli-service": "^4.5.13",`
`"@vue/test-utils": "1.0.3",`


Adding the resolve "hack" does not work.

**Comment by jarvelov** [comment]
Hi, have you tried replacing how VFJS is imported?

Replace

`import VueFormJsonSchema from 'vue-form-json-schema';`

with

`import VueFormJsonSchema from 'vue-form-json-schema/dist/vue-form-json-schema.esm.js';`

**Comment by nexorianus** [comment]
Can confirm!
With the direct import of the ESM file, everything works fine.
